import argparse
import json
from pathlib import Path

parser = argparse.ArgumentParser(
    prog="Mask MUMPS Comments",
    description="Replace MUMPS comments with numbers, to be used in MadLibs-style"
    " automatic documentation evaluation.",
)

parser.add_argument(
    "--input-comments-file",
    type=str,
    required=True,
    help="The .json file generated by `mask_mumps_comments.py`",
)

parser.add_argument(
    "--output-dir",
    type=str,
    required=True,
    help="The directory containing the generated .json files",
)

args = parser.parse_args()
input_file = Path(args.input_comments_file).expanduser()
output_dir = Path(args.output_dir).expanduser()

master_obj = json.loads(input_file.read_text())
for comment_file in output_dir.rglob("*.json"):
    key = comment_file.with_suffix(".m").name
    if key not in master_obj:
        print(f"Skipping file: {comment_file.name}")
    obj = json.loads(comment_file.read_text())
    master_obj[key]["generated_comments"] = obj


(output_dir / "processed.json").write_text(json.dumps(master_obj))
