name: Publish PyPi Package

on:
  push:
    branches:
      - public
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
      volumes:
        - public:/public
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1

      - name: Install Prerequisites 🖥️
        run: |
          apt update
          apt install rsync -y
          python --version
          curl -sSkL https://install.python-poetry.org | python -
          export PATH=$PATH:$HOME/.local/bin
          poetry --version

      - name: Build 🛠️
        run: |
          export PATH=$PATH:$HOME/.local/bin
          poetry build

      - name: Deploy 🚀
        run: |
          export PATH=$PATH:$HOME/.local/bin
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish
